### ISSUE TITLE
Dont open 

### ISSUE THREAD

**Issue by Konohamaru160007** [HiDe-Techno-Tips/Blackeye-for-Windows#13]
![image](https://user-images.githubusercontent.com/100881339/156674481-903db025-c85a-45b3-bab6-b8bfaf741e15.png)

**Comment by HimDek** [comment]
[The instructions](https://github.com/HiDe-Techno-Tips/Blackeye-for-Windows#how-to-use] clearly says `cd Blackeye-for-Windows-main` and not `cd Blackeye-for-Windows` as you did.
