### ISSUE TITLE
Hi,I just follow your instruction but when I type in"blackeye.bat" it say command not found am I missing something?

### ISSUE THREAD

**Issue by digilx** [HiDe-Techno-Tips/Blackeye-for-Windows#19]
──(root㉿kali)-[/home/kali/Blackeye-for-Windows]
└─# blackeye.bat
blackeye.bat: command not found

**Comment by HiDe-Techno-Tips** [comment]
Why are you using it in Linux? Its for Windows as said by the name itself.

**Comment by HimDek** [comment]
No reply by author.

**Comment by genius9999999** [comment]
I'm using windows and it says the same thing
