### ISSUE TITLE
Failed to complete tunnel connection

### ISSUE THREAD

**Issue by littleblack111** [HiDe-Techno-Tips/Blackeye-for-Windows#23]
![image](https://user-images.githubusercontent.com/97672521/176172517-bcf57bdd-c308-4cc9-9c49-041c05cfeb24.png)
when I try to connnect localhost(Chinease)(can't connect)
![image](https://user-images.githubusercontent.com/97672521/176173040-5f32a506-9251-4637-bf9f-100e46999882.png)
![image](https://user-images.githubusercontent.com/97672521/176173372-a2bfc000-8e42-44ee-bfed-cf2d547bf707.png)

**Comment by littleblack111** [comment]
Do I have to do Port Forwarding??

**Comment by HimDek** [comment]
Your device's antivirus or firewall is probably blocking the tunnel.
