### ISSUE TITLE
Error when entering choice

### ISSUE THREAD

**Issue by githubuser4619** [HiDe-Techno-Tips/Blackeye-for-Windows#5]
I have downloaded and extracted the folder and ran the bat file, when choosing which service to create a phish link for it opens a error dialog box saying cannot find php.exe in the folder. The php folder is also empty and i am not sure how to fix this

**Comment by HiDe-Techno-Tips** [comment]
I am working on this and it should be fixed by one or two days. Thanks for the report.

**Comment by HiDe-Techno-Tips** [comment]
It has been fixed in [Version 1.1.6](https://github.com/HiDe-Techno-Tips/Blackeye-for-Windows/releases/tag/v1.1.6).
