### ISSUE TITLE
php folder is empty

### ISSUE THREAD

**Issue by githubuser4619** [HiDe-Techno-Tips/Blackeye-for-Windows#6]
the php folder in blackeye for windows is empty, and when clicking the generated link it says this 
![image](https://user-images.githubusercontent.com/74836718/132372903-2c0c69bd-8ccb-4fed-b7e3-ae02ec23a874.png)

**Comment by HiDe-Techno-Tips** [comment]
Duplicate of #5

**Comment by HiDe-Techno-Tips** [comment]
It has been fixed in [Version 1.1.6](https://github.com/HiDe-Techno-Tips/Blackeye-for-Windows/releases/tag/v1.1.6)
