### ISSUE TITLE
Facebook 

### ISSUE THREAD

**Issue by dragonboykk** [HiDe-Techno-Tips/Blackeye-for-Windows#8]
Hi thank you for your blackeye software. facebook login doesnt show login information.can u fix it please?

**Comment by HiDe-Techno-Tips** [comment]
Update to [Latest version](https://github.com/HiDe-Techno-Tips/Blackeye-for-Windows/releases/latest) and try.

**Comment by derpmanoli** [comment]
localhost40:40 error?
