### ISSUE TITLE
No link

### ISSUE THREAD

**Issue by nightsky869** [HiDe-Techno-Tips/Blackeye-for-Windows#9]
I am getting all the way through but it is not generating a link that I can use

**Comment by nightsky869** [comment]
Found fix

**Comment by MinntFM** [comment]
what was the fix?

**Comment by jwyatt4** [comment]
i would like to know what the fix was as well i cant get the link to appear

**Comment by genius9999999** [comment]
> Found fix



> Found fix



> Found fix

What was it?
